controller_manager:
  ros__parameters:
    update_rate: 200  # Hz
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    position_controller:
      type: position_controllers/JointGroupPositionController
    
position_controller:
 ros__parameters:
   joints:
     - joint_j0
     - joint_j1
     - joint_j2
     - joint_j3
